JNG-3176 add workflows and update .xml files
BlackBeltTechnology/karaf-features-antlr pull request #3
Opened 2022-01-21 13:18 UTC by FarkasValentin

2022-01-27 17:17 UTC, robertcsakany requested changes

2022-01-27 17:17 UTC, robertcsakany commented on .flattened-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file have to be removed and added to .gitignore

2022-01-27 17:17 UTC, robertcsakany commented on features/.flattened-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file have to be removed and added to .gitignore

2022-01-28 11:47 UTC, noherczeg approved these changes

2022-01-31 07:52 UTC, merged